Ashutosh00710/github-readme-activity-graph

src/svgs.ts, styles/graphAnimation.ts
=> Changed strokeAnimation to pointAnimation

__test__/index.test.js, __test__/inputs.index.js, package-lock.json, src/utils.ts
=> Added tests for svgs and typo fix

README.md, package-lock.json
Hi,
I saw the issue that there  was a need to add table of contents in readme file, I've added some content about contributing.
Happy to make other changes and will check others docs for work. Thank you.
2. [ ] Have you lint your code locally prior to submission?
- 
> [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
=> table of contents added in readme file

__test__/__snapshots__/svgs.test.js.snap, src/svgs.ts
=> Added header to the graph which links back to main repo

README.md, __test__/fakeInputs.js, interfaces/interface.ts, src/utils.ts
Added docs to Readme for `hide_border` (introduced in #52).
Also changed to use snake case instead of camel case for consistency with existing parameters.
=> Add hide border info to Readme

README.md, interfaces/interface.ts, src/utils.ts
Okay so i've added the options `hide_title` and `custom_title` to the query string.
I tried to implement `hide_title` as a boolean (like `area`) but for some reason that caused the build to fail.. so i've implemented it as a true/false string.
In the utils file i've added the appropriate logic to update the title based on these arguments.
I've also updated the README to include these new features.
Let me know if you have any feedback. If you like what i've done I have a few more ideas and could put in more pull requests.
Thanks,
Jacob
=> Title Updates

styles/themes.ts
I updated the `areaColor` of each theme to match the line color for that theme. The effect is subtle yet noticeable and looks better than one generic color for all themes.
=> Themes Update

THEMES.md, __test__/fakeInputs.ts, __test__/themes.test.ts, asset/material-palenight.svg, styles/themes.ts
=> Added Material Palenight Theme

THEMES.md, asset/gotham.svg, package-lock.json, styles/themes.ts
**SOLVES ISSUE** #25 partially.
**Changes Made**
1. File modified = `styles/theme.ts`
2. Added params for `gotham` theme taking hex values from other repos like `github-readme-stats`. [Here](https://camo.githubusercontent.com/cf6b1611c3b67ce94d8663a4b6ae14dc135b04a1233cb2bf01200d50aa0ad7b5/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a72612673686f775f69636f6e733d7472756526686964653d636f6e74726962732c7072732663616368655f7365636f6e64733d3836343030267468656d653d676f7468616d) is the inspiration.
**SCREENSHOTS**
I have personally used this in my own [`README.md`](https://github.com/sreyan-ghosh/sreyan-ghosh). Here is a …
=> added gotham theme (ref: #25)

THEMES.md, asset/monokai.svg, asset/noctis-minimus.svg, asset/one-dark.svg, styles/themes.ts
Issue: #25 
1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?
Monokai
Noctis Minimus
One dark
=> Noctis minimus

THEMES.md, asset/aqua.svg, asset/elegant.svg, index.html, script.js, src/main.ts, styles.css, styles/themes.ts
2. [ ] Have you lint your code locally prior to submission?
=> Contributed - web UI/UX and themes - elegant & aqua

index.html
I implemented the logo.png under /asset in the index.html, so that it will be shown as favicon in the web interface.
___
___
=> Added icon to web interface

CONTRIBUTING.md
Hello! @Ashutosh00710 and @Kshitij978 
&nbsp;&nbsp;&nbsp;   I have fixed a few grammatical mistakes in `CONTRIBUTING.md`, please review this contribution.
-  Create a `.env` file in **~root~ the root** directory and in there write
- Pull from the upstream again before you commit your **~changes, like~ changes as** you did in step 3. This is to ensure you still have the latest code.
- If you see **~a error~ an error** like
- Give **~sample~ a sample** code if you can.
=> Fix: CONTRIBUTING.md grammar

README.md
Adding myself to the list as suggested in https://github.com/Ashutosh00710/github-readme-activity-graph/pull/126#issuecomment-1163986937.
=> Add a contributor

src/GraphCards.ts
[Issue Link](https://github.com/Ashutosh00710/github-readme-activity-graph/issues/144)
2. [ ] Have you lint your code locally prior to submission?
=> adding zero index to Y axis

README.md
Grammatical errors is being fixed at various places.
- [+] Have you followed the guidelines in our Contributing document?
- [+ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
1. [+ ] Does your submission pass tests?
2. [+] Have you lint your code locally prior to submission?
- [+] Have you added an explanation of what your changes do and why you'd like us to include them?
- [+] Have you written new tests for your core changes, as applicable?
- [+] Have you successfully ran tests with your changes locally?
=> Fixes Grammatical errors

index.html, styles.css
=> Hover_Effect_at_social_issue#150

__test__/__snapshots__/svgs.test.ts.snap, __test__/utils.test.ts, src/svgs.ts
Fix #130 
2. [ ] Have you lint your code locally prior to submission?
=> #130 Fix displaying of border corner

script.js
=> fix: variable and function naming, code refactor

index.html, styles.css
=> update: color input style, fix: input & form container width

replit.sh
Added 'npm run build' command in replit.sh file
=> Fix issue #175

README.md
https://github.com/Ashutosh00710/github-readme-activity-graph/pull/186
=> Added myself to contributers

THEMES.md, asset/github-dark-dimmed.svg, src/styles/themes.ts
This change add github-dark-dimmed theme option.
[![Fabiano Couto's github activity graph](https://fabianocouto-activity-graph.vercel.app/graph?username=fabianocouto&theme=github-dark-dimmed&area=true&radius=6)](https://github.com/ashutosh00710/github-readme-activity-graph)
=> add github-dark-dimmed theme
